### ISSUE TITLE
Problem while running step 7 in Windows

### ISSUE THREAD

**Issue by plyhdrn** [MIT-CAVE/rc-cli#11]
While executing the command listed in step 7 in Windows, I'm experiencing the following issue:

`bash <(curl -s https://raw.githubusercontent.com/MIT-CAVE/rc-cli/main/install.sh) \
https://cave-competition-app-data.s3.amazonaws.com/amzn_2021/data.tar.xz`

I receive the following error when I run the command:

`Creating application folder at '/root/.rc-cli'...done
Cloning into '/root/.rc-cli'...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 60 (delta 5), reused 32 (delta 1), pack-reused 0
Receiving objects: 100% (60/60), 45.04 KiB | 4.50 MiB/s, done.
Resolving deltas: 100% (5/5), done.
Copying data down from https://cave-competition-app-data.s3.amazonaws.com/amzn_2021/data.zip...
done
Decompressing downloaded data...
[/root/.rc-cli/data.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /root/.rc-cli/data.zip or
        /root/.rc-cli/data.zip.zip, and cannot find /root/.rc-cli/data.zip.ZIP, period.
/dev/fd/63: Unable to access data from https://cave-competition-app-data.s3.amazonaws.com/amzn_2021/data.zip. Installation Canceled
`

I've tried manually installing the .zip data, but when I go to the URL, I get the following error:
`<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>cave-competition-app-data</BucketName>
<RequestId>PMTBJWXH7N893VFW</RequestId>
<HostId>bW1apTx0CIs/TkAJLMAIgBH+SQ7TdV4f/j7D38d4Ixf/kbs+oRNzscJ/LlNWsWNOhmocKDyXONE=</HostId>
</Error>`

It is crucial for me because I intend to utilize this tool to evaluate my Amazon Routing Challenge solution for my undergraduate project.

**Comment by connor-makowski** [comment]
Thanks for reaching out. Let's see what we can do.

@luisvasq Can you look into this?

**Comment by luisvasq** [comment]
Hi @plyhdrn!,

The Amazon contest data is no longer hosted in the S3 bucket link included by default in the installation process. I'll see if the contest data is still open and available at an alternate location and get back to you.

**Comment by luisvasq** [comment]
@plyhdrn, we've just released a new version of the `rc-cli` with updated instructions on how to install the CLI and retrieve the data. The new command is simply:
```sh
bash <(curl -s https://raw.githubusercontent.com/MIT-CAVE/rc-cli/main/install.sh)
```
Notice that the data URL is no longer included. After the installation, you must retrieve the data from the [official registry in AWS](https://registry.opendata.aws/amazon-last-mile-challenges/). Please take a look at [these instructions](https://github.com/MIT-CAVE/rc-cli#download-your-dataset) and you should be all set! :)

Luis
